%%{init: {
 'theme': 'base',
 'themeVariables': {
   'background': '#ffffff',
   'primaryColor': '#ffffff',
   'primaryTextColor': '#000000',
   'primaryBorderColor': '#000000',
   'lineColor': '#000000',
   'secondaryColor': '#ffffff',
   'tertiaryColor': '#ffffff'
 },
 'themeCSS': '.node rect, .node circle, .node polygon, .node path, .cluster rect { stroke: #000000 !important; stroke-width: 1px !important; filter: none !important; box-shadow: none !important; } .label { color: #000000 !important; }'
}}%%

flowchart TD
    subgraph HW["CAPA DE MAQUINARI I SENYALS"]
        Sensor["Sensor / Càmera IP"]
        DBus["D-Bus\ncom.lanaccess.sysevents"]
        Sensor -- "Hardware Interrupt" --> DBus
    end

    subgraph ALARM["MICROSERVEI LA-CORE-ALARM"]
        dbus_thread["dbus_listen_alarms_thread"]
        alarm_queue["global_alarm_queue\n(SafeQueue)"]
        db_client["db_client_thread"]
        EmissionQueue["global_emission_queue"]
        WsThread["ws_emit_alarms_thread"]
        dbus_thread -- "Enqueue" --> alarm_queue
        alarm_queue -- "Dequeue & Process" --> db_client
        db_client -- "Confirmació OK\n(Enqueue EmissionData)" --> EmissionQueue
        EmissionQueue --> WsThread
    end

    subgraph DBENG["MICROSERVEI LA-DB-ENGINE"]
        DBSvcImpl["DatabaseServiceImpl"]
        SQLite3Engine["SQLite3 Engine"]
        RemoteVFS["Remote VFS Driver"]
        DBSvcImpl -- "Prepare & Exec SQLite3" --> SQLite3Engine
        SQLite3Engine -- "Intercept Read/Write Operations" --> RemoteVFS
    end

    subgraph VIDENG["MICROSERVEI LA-VIDEO-ENGINE"]
        IOListener["IO Server Listener"]
        DiskDriver["Hardware Disk Driver"]
        Storage[(Físic Flash/HDD Storage)]
        IOListener -- "Direct Block I/O Operations" --> DiskDriver
        DiskDriver --> Storage
    end

    NGINX["Proxy NGINX"]
    FrontendAngular["Frontend Angular"]

    DBus -- "Signal ALARM_NOTIFY" --> dbus_thread
    db_client -- "gRPC Execute/Query\n(unix:// socket)" --> DBSvcImpl
    DBSvcImpl -- "gRPC Response OK" --> db_client
    RemoteVFS -- "Unix Domain Socket\n/tmp/io.sock (IoRequest)" --> IOListener
    WsThread -- "JSON string over libwebsockets" --> NGINX
    NGINX -- "WSS" --> FrontendAngular
