graph TD
    Usuari([Usuari])
    WCV[web core view]
    NGX[NGINX]
    CL[core legacy]
    DBUS{{dbus}}
    CN[core notifier]
    CA[core alarm]
    DBE[db engine]
    DBV[video engine]
    Disk[(Disk)]

    Usuari -- UI --> WCV
    WCV -- UI --> Usuari

    WCV -- https / wss --> NGX
    NGX -- http --> CL
    NGX -- ws --> CN
    NGX -- ws --> CA
    NGX -- WHEP --> DBV
    WCV -- UDP/SRTP --> DBV

    CL --> DBUS
    DBUS --> CN
    DBUS --> CA

    CA -- gRPC --> DBE
    DBE -- unix --> DBV

    DBV -- FS2 --> Disk
    Disk -- FS2 --> DBV
