classDiagram
    class Alarm {
        +String alarm_id
        +String db_id
        +String description
        +DateTime timestamp
        +String priority
        +String status
        +boolean is_read
        +boolean is_archived
    }

    class User {
        +String id
        +String name
        +String profile
        +String grants
    }

    class IoItem {
        +String id
        +String name
        +String topic
        +String data
        +String[] capabilities
    }

    class Camera {
        +String id
        +String name
        +String type
        +String logicId
        +String systemId
        +IpConfig ipConfig
        +Preset[] presets
        +Codec[] codecList
    }

    class Codec {
        +String rtspUri
        +int width
        +int height
        +int fps
        +int kbps
        +String profileToken
    }

    class Preset {
        +String name
        +String token
        +String position
    }

    Alarm --> Camera : associada a
    User ..> Camera : té permisos sobre
    Camera *-- Codec : conté
    Camera *-- Preset : conté
