%%{init: {
 'theme': 'neutral',
 'themeVariables': {
   'background': '#ffffff',
   'primaryColor': '#ffffff',
   'primaryTextColor': '#000000',
   'primaryBorderColor': '#000000',
   'lineColor': '#000000',
   'secondaryColor': '#ffffff',
   'tertiaryColor': '#ffffff',
   'noteBkgColor': '#ffffff',
   'noteTextColor': '#000000'
 },
 'themeCSS': '.outer-path path:first-child { fill: #ffffff !important; } .outer-path path:not(:first-child) { stroke: #000000 !important; } .divider path { stroke: #000000 !important; } .relation { stroke: #000000 !important; } .relationshipLabelBox { fill: #ffffff !important; opacity: 1 !important; } marker path { fill: #000000 !important; stroke: #000000 !important; }'
}}%%

classDiagram
  direction LR

  class NVR {
    +versioFirmware : String
    +estat : Connected | Offline
  }

  class Camara {
    +id : String
    +nom : String
    +adrecaIP : String
    +codec : H264 | H265
    +estat : Connected | Disconnected | Error
  }

  class Flux {
    +protocol : WebRTC | HLS
    +estat : Actiu | Inactiu
    +latencia : ms
  }

  class Gravacio {
    +id : String
    +timestamp : DateTime
    +duracio : Integer
    +tipusGravacio : Continua | Alarma
  }

  class Alarma {
    +id : String
    +timestamp : DateTime
    +tipus : Sensor | Rele | Sistema | Video
    +estat : NoLlegida | Llegida | Arxivada
  }

  class Usuari {
    +id : String
    +nom : String
    +rol : Administrador | Operador
    +grants : String[]
  }

  class Sessio {
    +keepAliveInterval : 60s
    +estat : Activa | Expirada
  }

  class ConfigLock {
    +idModul : String
    +expiresIn : 30 | 120
    +ultimaRenovacio : DateTime
  }

  class DispositiuIO {
    +id : String
    +nom : String
    +tipus : Input | Output
    +estat : Actiu | Inactiu
  }
  NVR "1" --> "0..*" DispositiuIO : gestiona

  NVR "1" --> "0..151" Camara : conté
  NVR "1" --> "0..*" Alarma : genera (Sistema)
  
  Camara "1" --> "0..2" Flux : produeix
  Camara "1" --> "0..*" Gravacio : emmagatzema
  Camara "1" --> "0..*" Alarma : genera (Vídeo/Analítica)
  
  Usuari "1" --> "0..*" Sessio : inicia
  Usuari "0..1" --> "0..1" ConfigLock : posseeix
