mindmap
  root((WebCoreView))
    Estils
      Open Sans Typography
      Vanilla CSS / SCSS
      Responsive Design
    TypeScript
    Frontend
      Signals / State Management
      Reactive Forms
      Angular 19
    Docs
      NPM
      Eines i Processos
        Angular CLI
        Git / GitHub
    Comunicació
      RTSP / Streaming
      HLS
      HTTP / REST API
      Real-time
    Conceptes d'Enginyeria
      Grants/Permissions
      Network Security
      System Maintenance
      Locking
